# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: phpstan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: PHPStan
        uses: docker://bitnami/php-fpm:latest
        run: |
          composer install
          php vendor/bin/phpstan analyse -c phpstan.dist.neon
